# @package checkpoint

# Checkpoint monitoring settings
monitor: "loss"
mode: "min"  # min or max

# Checkpoint file settings
filename_template: "checkpoint_epoch{epoch}_loss{metric}_{timestamp}.pth"
state_dict_key: "model_state"
optimizer_state_dict_key: "optimizer_state"

# Loading and saving strategies
load_strategy: "accelerated"  # accelerated or raw
save_strategy: "accelerated"  # accelerated or raw

# Validation settings
strict_validation: true  # whether to strictly validate model configs during loading

# Checkpoint operations
pre_load_ops: []  # operations to apply before loading checkpoint
ckpt_transforms: []  # transformations to apply to checkpoint during loading