order: ['freeze_all_params', 'print_optimizing_params']


freeze_weights:
  _target_: operations.PostLoadOpsHandler.freeze_weights


freeze_all_params:
  _target_: operations.PostLoadOpsHandler.freeze_all_params


freeze_all_biases:
  _target_: operations.PostLoadOpsHandler.freeze_all_biases

unfreeze_all_biases:
  _target_: operations.PostLoadOpsHandler.unfreeze_all_biases


unfreeze_all_parameters:
  _target_: operations.PostLoadOpsHandler.unfreeze_all_parameters


print_optimizing_params:
  _target_: operations.PostLoadOpsHandler.print_optimizing_params


save_onnx:
  _target_: operations.PostLoadOpsHandler.save_onnx
  input_shape: [1, 3, 32, 32]
  save_path: ${paths.experiment_dir}/pruned_model.onnx

remove_parametrizations:
  _target_: operations.PostLoadOpsHandler.remove_parametrization