# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other

defaults:
  - _self_
  - hydra: default.yaml
  - extras: default.yaml


  # indices
  - /training_components/transform/loss/index@index.LT
  - /training_components/transform/input/index@index.IT
  - /training_components/loss/index@index.LOSSES

  
  - checkpoint/default@checkpoint_load
  - checkpoint/default@checkpoint_save
  
  - paths: default
  - training_components: default
  - datamodule: null
  - model: null
  - experiment: null

# configurable
project_name: transairaw # < project name used for folder creation
base_path: './' # base path where everything will be stored
exp_name: "debug_mlflow" # experiment name
exp_num: 0 # experiment number
        
# start setup
seed: 228
entry_point: accelerator # entry point specified in MLProject
nnodes: 1
nproc_per_node: 8
gpu_idxs: ~


tags: ['dev', 'debug']


verify_model: False
verify_dataloader: False
verify_loss: False


load_from_previous: False

job_name: ${zero_pad:${exp_num}, 4}_${exp_name}
attempt_id: ${uuid4:8}